Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -20,3 +20,8 @@ jobs:
         run: npm ci
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v2
+      - name: Fail on High Severity
+        if: ${{ steps.analyze.outputs.alerts-count-severity-high }} != '0'
+        run: |
+          echo "High-severity vulnerabilities found. Failing."
+          exit 1
